Pin the Solr version to v9.6.0
**ISSUE**
Solr has deprecated configuration options still used by solr_wrapper.
This results in the following error when attempting to start
solr_wrapper
```
.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/solr_wrapper-4.2.0/lib/solr_wrapper/instance.rb:366:in `exec': Failed to execute solr create: Option '-url': Deprecated for removal since 9.7: Use -s instead (RuntimeError)
Option '-url': Deprecated for removal since 9.7: Use -s instead

ERROR: Error from server at http://127.0.0.1:8983/solr/admin/cores?action=CREATE&name=blacklight-core&instanceDir=blacklight-core&wt=javabin&version=2: Error CREATEing SolrCore 'blacklight-core': Unable to create core [blacklight-core] Caused by: Can't find resource 'solrconfig.xml' in classpath or '/private/var/folders/xz/hm89v2r10z3f82g038c4ng500000gn/T/solr-9.9.0/server/solr/blacklight-core'
```

**RESOLUTION**
Temporarily pin the Solr version to a version prior to the version
where the configuration options were deprecated.